export enum ChickenAiStates {
    START_WANDERING = 'START_WANDERING',
    WANDERING = 'WANDERING',
    START_IDLING = 'START_IDLING',
    IDLING = 'IDLING',
    START_IDLING_LOOKING = 'START_IDLING_LOOKING',
    IDLING_LOOKING = 'IDLING_LOOKING',
    GO_TO_EAT = 'GO_TO_EAT',
    GO_TO_DRINK = 'GO_TO_DRINK'
}
